# CyberForce 2023
# Dfir-Jesseee
#
# run this to move file over to Windows machine 
---
- hosts: windows
  tasks:
  - name: Copy a single file
    win_copy:
      src: "{{ playbook_dir }}/files/velociraptor-v0.6.8-windows-amd64.exe"
      dest: C:\Users\Public\velociraptor6-8.exe

#  - name: Set-Location to Public Folder
#    win_shell: |
#        Set-Location C:\Users\Public\

#  - name: RUN script to INSTALL SYSMON & SYSMOD
#    win_shell: cmd /K Powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -File C:\Users\Public\velociraptor6-8.exe
#
# Debug
#  - name: run a powershell script
#    script: C:\Users\Public\invoke_win_Wazuh_agent.ps1
#    register: out
#   - debug: var=out
