- hosts: debian
  become: true
  vars:
    container_count: 1
    default_container_name: vintage-computing
    default_container_image: jgoerzen/vintage-computing
    default_container_command: start
  tasks:
    - name: Ensure Docker image is present
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull
        state: present

    - name: Create or update Docker container
      community.docker.docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present
        update: true
      register: container_result

    - name: Start Docker container
      community.docker.docker_container:
        name: "{{ default_container_name }}"
        state: present
#      when: container_result.changed or container_result.status == 'created'
