---
- hosts: debian
  become: true
  vars:
    container_count: 1
    default_container_name: vintage-computing
    default_container_image: jgoerzen/vintage-computing
    default_container_command: start

  tasks:
#    - name: Add commands to make the mounpoint thing not error
#      ansible.builtin.shell: |
#        sudo mkdir /sys/fs/cgroup/systemd 2>/dev/null
#        sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd 2>/dev/null

    - name: Pull default Docker image
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      community.docker.docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present
      with_sequence: count={{ container_count }}

#    - name: Start Docker container
#      community.docker.docker_container:
#        name: vintage-computing
#        image: jgoerzen/vintage-computing
#        command: jgoerzen/vintage-computing vint pdp11-2bsd
#        state: start
#        interactive: true
#        tty: true


    - name: Start docker container VintagePC
      shell: |
        sudo docker run -d jgoerzen/vintage-computing vint pdp11-2bsd \
#        sudo docker run -p 2323:23 -d jgoerzen/vintage-computing vint pdp11-2bsd \

#        sudo docker run --rm --init jgoerzen/vintage-computing vint pdp11-2bsd \
#        sudo docker run -d --name "{{ default_container_name }}" "{{ default_container_image }}" "{{ default_container_command }}" \
#        sudo docker run -ti jgoerzen/vintage-computing vint \
#        docker run jgoerzen/vintage-computing vint \
#          -p 82:82 \
#          -p 444:444 \
#          jgoerzen/vintage-computing \
#
# run ansible adhoc cmd instead of above shell... 
# ansible ubuntu -a "docker run --name simplerisk -d -p 81:81 -p 443:443 simplerisk/simplerisk"
#
# Open Browser to https://IPofServer:443
# STOP and Remove all containers: sudo docker container stop $(docker container ls -aq)

# have student go into the docker container to see whats going on->
# sudo docker exec -it zen_chatelet vint pdp11-2bsd

#Or have Students do the below
# sudo docker run -ti jgoerzen/vintage-computing vint pdp11-2bsd

# onec your in the docker container as pdp11-2bsd select "Enter"
# Then CTRL + D to enter multiUser Mode
#  Once it finishes booting into multiuser mode,
# you can log in on the console as root with a password of Hithere.
# Then checkout https://histinf.blogs.upv.es/2010/11/29/pdp-11-de-digital-equipment-corp/
# CTRL + E will exit PDP11
# then
# sim> exit
