---
- hosts: ubuntu
  become: true
#  vars:
#    container_count: 1
#    default_container_name: dvca
#    default_container_image: mainframed767/dvca
#    default_container_command: start

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
#          - socat
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Starting docker service
      service:
        name: docker
        state: started
        enabled: yes
#    - name: Clone a repo
#      ansible.builtin.git:
#        repo: https://github.com/jessefmoore/Docker_Backdoors-Breaches.git
#        dest: ~/Docker_Backdoors-Breaches
#        single_branch: yes
#        version: main

#    - name: Pull default Docker image
#      community.docker.docker_image:
#        name: "{{ default_container_image }}"
#        source: pull

#    - name: Create default containers
#      community.docker.docker_container:
#        name: "{{ default_container_name }}{{ item }}"
#        image: "{{ default_container_image }}"
#        command: "{{ default_container_command }}"
#        state: present
#      with_sequence: count={{ container_count }}


#    - name: Run multiple commands to start docker container
#      shell: |
#        sudo docker build -t bb-game .
#        sudo docker run -d -p 8084:80
